### ISSUE TITLE
Wrong FF value on the first reading

### ISSUE THREAD

**Issue by karolpawlowski** [harness/ff-python-server-sdk#31] opened 2022-06-14 11:52 UTC
Hey, I'm trying your Python SDK and was doing an example. I thought that something doesn't work on my side because I've god `False` value when calling `client.bool_variation`.

```
try:
    ff_identifier = "harness"
    client = CfClient("api_key")
    target = Target(identifier=ff_identifier)
    FLAGS["departments"] = client.bool_variation("Departments", target, False)
    FLAGS["org_module_visibility"] = client.bool_variation("org_module_visibility", target, False)
    LOG.warning("FLAGS %s", FLAGS)
except Exception as e:
    LOG.error(f"Something FF wrong: {e}")
```

I was a little surprised when I used an approach from your example with infinite while loop checking the flag every 10 seconds.

```
try:
    ff_identifier = "harness"
    client = CfClient("api_key")
    target = Target(identifier=ff_identifier)
    while True:
        FLAGS["departments"] = client.bool_variation("Departments", target, False)
        FLAGS["org_module_visibility"] = client.bool_variation("org_module_visibility", target, False)
        LOG.warning("FLAGS %s", FLAGS)
        time.sleep(10)

except Exception as e:
    LOG.error(f"Something FF wrong: {e}")
```

Output:

```
metrikus-app-platform-api-gateway-1  | 2022-06-14T11:38:46.107432Z [debug    ] CfClient initialized           [featureflags.util]
metrikus-app-platform-api-gateway-1  | Starting PollingProcessor with request interval: 60
metrikus-app-platform-api-gateway-1  | 2022-06-14T11:38:46.623185Z [info     ] Starting PollingProcessor with request interval: 60 [featureflags.util]
metrikus-app-platform-api-gateway-1  | Starting StreamingProcessor connecting to uri: https://config.ff.harness.io/api/1.0/stream?cluster=2
metrikus-app-platform-api-gateway-1  | 2022-06-14T11:38:46.628861Z [info     ] Starting StreamingProcessor connecting to uri: https://config.ff.harness.io/api/1.0/stream?cluster=2 [featureflags.util]
metrikus-app-platform-api-gateway-1  | Loading target segments
metrikus-app-platform-api-gateway-1  | 2022-06-14T11:38:46.637002Z [debug    ] Loading target segments        [featureflags.util]
metrikus-app-platform-api-gateway-1  | Starting AnalyticsService with request interval: 60
metrikus-app-platform-api-gateway-1  | 2022-06-14T11:38:46.650029Z [warning  ] FLAGS {'departments': False, 'org_module_visibility': False} [platform_api_gateway.main]
metrikus-app-platform-api-gateway-1  | Loading feature flags
metrikus-app-platform-api-gateway-1  | 2022-06-14T11:38:46.661046Z [info     ] Starting AnalyticsService with request interval: 60 [featureflags.util]
metrikus-app-platform-api-gateway-1  | 2022-06-14T11:38:46.661691Z [debug    ] Loading feature flags          [featureflags.util]
metrikus-app-platform-api-gateway-1  | Target segments loaded
metrikus-app-platform-api-gateway-1  | 2022-06-14T11:38:47.028013Z [debug    ] Target segments loaded         [featureflags.util]
metrikus-app-platform-api-gateway-1  | Setting the cache segment value Test_Group
metrikus-app-platform-api-gateway-1  | 2022-06-14T11:38:47.030176Z [debug    ] Setting the cache segment value Test_Group [featureflags.util]
metrikus-app-platform-api-gateway-1  | Feature flags loaded
metrikus-app-platform-api-gateway-1  | 2022-06-14T11:38:47.045732Z [debug    ] Feature flags loaded           [featureflags.util]
metrikus-app-platform-api-gateway-1  | Setting the cache value bms_module_visibility
metrikus-app-platform-api-gateway-1  | 2022-06-14T11:38:47.046922Z [debug    ] Setting the cache value bms_module_visibility [featureflags.util]
metrikus-app-platform-api-gateway-1  | Setting the cache value Departments
metrikus-app-platform-api-gateway-1  | 2022-06-14T11:38:47.047913Z [debug    ] Setting the cache value Departments [featureflags.util]
metrikus-app-platform-api-gateway-1  | Setting the cache value devices_tab
metrikus-app-platform-api-gateway-1  | 2022-06-14T11:38:47.049034Z [debug    ] Setting the cache value devices_tab [featureflags.util]
metrikus-app-platform-api-gateway-1  | Setting the cache value global_search
metrikus-app-platform-api-gateway-1  | 2022-06-14T11:38:47.050463Z [debug    ] Setting the cache value global_search [featureflags.util]
metrikus-app-platform-api-gateway-1  | Setting the cache value home_tab
metrikus-app-platform-api-gateway-1  | 2022-06-14T11:38:47.051699Z [debug    ] Setting the cache value home_tab [featureflags.util]
metrikus-app-platform-api-gateway-1  | Setting the cache value insights_tab
metrikus-app-platform-api-gateway-1  | 2022-06-14T11:38:47.052677Z [debug    ] Setting the cache value insights_tab [featureflags.util]
metrikus-app-platform-api-gateway-1  | Setting the cache value map_tab
metrikus-app-platform-api-gateway-1  | 2022-06-14T11:38:47.053621Z [debug    ] Setting the cache value map_tab [featureflags.util]
metrikus-app-platform-api-gateway-1  | Setting the cache value org_module_visibility
metrikus-app-platform-api-gateway-1  | 2022-06-14T11:38:47.054808Z [debug    ] Setting the cache value org_module_visibility [featureflags.util]
metrikus-app-platform-api-gateway-1  | Setting the cache value settings_tab
metrikus-app-platform-api-gateway-1  | 2022-06-14T11:38:47.055607Z [debug    ] Setting the cache value settings_tab [featureflags.util]
metrikus-app-platform-api-gateway-1  | Setting the cache value toaster_visibility
metrikus-app-platform-api-gateway-1  | 2022-06-14T11:38:47.056653Z [debug    ] Setting the cache value toaster_visibility [featureflags.util]
metrikus-app-platform-api-gateway-1  | PollingProcessor initialized ok
metrikus-app-platform-api-gateway-1  | 2022-06-14T11:38:47.057709Z [info     ] PollingProcessor initialized ok [featureflags.util]
metrikus-app-platform-api-gateway-1  | Poller is in pause mode...
metrikus-app-platform-api-gateway-1  | 2022-06-14T11:38:47.058406Z [debug    ] Poller is in pause mode...     [featureflags.util]
metrikus-app-platform-api-gateway-1  | 2022-06-14T11:38:56.682252Z [warning  ] FLAGS {'departments': True, 'org_module_visibility': True} [platform_api_gateway.main]
metrikus-app-platform-api-gateway-1  | 2022-06-14T11:39:06.704829Z [warning  ] FLAGS {'departments': True, 'org_module_visibility': True} [platform_api_gateway.main]
```

As you see the first LOG output was: `FLAGS {'departments': False, 'org_module_visibility': False}`. The second and following are `FLAGS {'departments': True, 'org_module_visibility': True}` which is correct but I don't change flag values. The first value was wrong.

Is it intended behaviour?

**Environment:**
- harness-featureflags==1.0.6
- python:3.8-slim docker image

**Comment by karolpawlowski** [comment] 2022-06-15 07:47
Furthermore, the second reading in a row doesn't help, but one second break does:

```
    FLAGS["departments"] = client.bool_variation("Departments", target, False)
    FLAGS["org_module_visibility"] = client.bool_variation("org_module_visibility", target, False)
    LOG.warning("FLAGS %s", FLAGS)

    FLAGS["departments"] = client.bool_variation("Departments", target, False)
    FLAGS["org_module_visibility"] = client.bool_variation("org_module_visibility", target, False)
    LOG.warning("SECOND READING FLAGS %s", FLAGS)
    
    for _ in range(10):
        time.sleep(1)
        LOG.warning("One sec break...")

        FLAGS["departments"] = client.bool_variation("Departments", target, False)
        FLAGS["org_module_visibility"] = client.bool_variation("org_module_visibility", target, False)
        LOG.warning("READING FLAGS %s", FLAGS)
```

Output:
```
metrikus-app-platform-api-gateway-1  | 2022-06-15T07:44:09.693677Z [warning  ] FLAGS {'departments': False, 'org_module_visibility': False} [platform_api_gateway.main]
metrikus-app-platform-api-gateway-1  | 2022-06-15T07:44:09.696202Z [warning  ] SECOND READING FLAGS {'departments': False, 'org_module_visibility': False} [platform_api_gateway.main]

metrikus-app-platform-api-gateway-1  | 2022-06-15T07:44:10.699466Z [warning  ] One sec break...               [platform_api_gateway.main]
metrikus-app-platform-api-gateway-1  | 2022-06-15T07:44:10.703933Z [warning  ] READING FLAGS {'departments': True, 'org_module_visibility': True} [platform_api_gateway.main]
metrikus-app-platform-api-gateway-1  | 2022-06-15T07:44:11.719364Z [warning  ] One sec break...               [platform_api_gateway.main]
metrikus-app-platform-api-gateway-1  | 2022-06-15T07:44:11.726016Z [warning  ] READING FLAGS {'departments': True, 'org_module_visibility': True} [platform_api_gateway.main]
```

**Comment by davejohnston** [comment] 2022-06-22 11:52
@karolpawlowski thanks for raising this.  The issue is that when the SDK starts up its starting async, so it will start evaluating straight away and returning the default value, until its pulled all the configuration from the FF service.

We have started to introduce a wait for initialisation call in the other SDKs but haven't updated Python yet.  This makes start up synchronous, so the first call to boolVariation will return what you expect.

**Comment by erdirowlands** [comment] 2023-08-01 10:18
`waitForInitialization` is now available https://github.com/harness/ff-python-server-sdk/releases/tag/1.1.8 

See an example here: https://github.com/harness/ff-python-server-sdk/blob/main/examples/wait_for_initialization_example/wait_for_initialization.py

Closing this issue

**Closed by erdirowlands** 2023-08-01 10:18 UTC
Labels: enhancement
